version: '3'

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/go/src/todo-api-server"
      - '/go/src/todo-api-server/vendor'
      # - ".:/go/src/github.com/k-tada/todo-api-server"
      # - '/go/src/github.com/k-tada/todo-api-server/vendor'
    environment:
      PORT: 9999
    ports:
      - '9999:9999'
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongo

